# RAG status tags
RAG_STATUS_RAG = "rag"
RAG_STATUS_NO_RAG = "no-rag"

# Resource type tags
RESOURCE_TYPE_PRESENTATION = "presentation"
RESOURCE_TYPE_IMAGE = "image"
RESOURCE_TYPE_MINDMAP = "mindmap"
RESOURCE_TYPE_EXAM = "exam"

# Generation type tags
GENERATION_TYPE_BATCH = "batch"
GENERATION_TYPE_STREAM = "stream"

# Convenience collections
RESOURCE_TYPES = [
    RESOURCE_TYPE_PRESENTATION,
    RESOURCE_TYPE_IMAGE,
    RESOURCE_TYPE_MINDMAP,
    RESOURCE_TYPE_EXAM,
]

GENERATION_TYPES = [GENERATION_TYPE_BATCH, GENERATION_TYPE_STREAM]
RAG_STATUSES = [RAG_STATUS_RAG, RAG_STATUS_NO_RAG]